version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./confs/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./confs/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      # Tip! Get strong password using: openssl rand -base64 32
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: VVPkbf4vYTybY3MZdGSBKiwiFQ43X1wO1ktezEtzeQI=
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./confs/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  adminer:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: adminer
    restart: unless-stopped
    tty: true
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local